package com.systemdesign.truecaller.model.common;

public enum Tag {

    EDUCATION,
    ENTERTAINMENT_ARTS,
    FINANCE_INSURANCE,
    GOVERNMENTAL_PUBLIC_SERVICES,
    HEALTH_WELLNESS,
    HOTEL_ACCOMODATION,
    NIGHTLIFE_DRINKS,
    RESTAURANT_CAFES,
    SERVICES,
    SHOPPING_CONVENIENCE_STORES,
    TRANSPORTATION_AUTOMOTIVE,
    TRAVEL_TOURISM,
    LEGAL,
    BEAUTY_PERSONAL_CARE,
    PROPERTY,
    RELIGIOUS_PLACE,
    SPORTS_RECREATION,
    RETAIL_DELIVERY
}
